HR_System/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('company/', include('company.urls')),
    path('employee/', include('employee.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

company/urls.py
from django.urls import path
from .views import branch_details , branches, branch_create , branch_edit


app_name = 'company'

# company/
urlpatterns = [
    path('', branches, name = "branches"),
    path('create-branch', branch_create, name="branch-create"),
    path('<int:branch_id>', branch_details, name="branchesDetails"),
    path('edit-branch/<int:id>', branch_edit, name="branch_edit"),


]

employee/urls.py
from django.urls import path
from .views import EmployeeList , EmployeeDetail , createEmployee ,DeleteEmployee ,UpdateEmployee


app_name = 'employee'

#employee/
urlpatterns = [
    path('',EmployeeList.as_view()),
    path('<int:pk>/',EmployeeDetail.as_view()),
    path('create',EmployeeList.as_view()),
    path('<int:pk>/update',UpdateEmployee.as_view()),
    path('<int:pk>',DeleteEmployee.as_view()),

]

company/models.py
from django.db import models

class Branch(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    phone = models.CharField(max_length=12, null = True , blank = True)
    email = models.EmailField(max_length=50, null = True , blank = True)

    def __str__(self):
        return self.name

class Department(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=200)
    branch = models.ForeignKey('Branch', related_name="departmentsBranch", on_delete=models.CASCADE)

    def __str__(self):
        return self.name

employee/models.py
from django.db import models

class Employee(models.Model):
    name = models.CharField(max_length=50)
    salary = models.IntegerField()
    birth_day = models.DateField
    age = models.IntegerField()
    position_id = models.ForeignKey('Position',related_name='position_id' , on_delete=models.CASCADE ,blank=True, null=True)

    def __str__(self):
        return self.name
    

class Position(models.Model):
    name = models.CharField(max_length=50)
    years_of_experience = models.IntegerField()
    desc = models.TextField(max_length=500)

    def __str__(self):
        return self.name
    

company/views.py
from django.shortcuts import render, redirect
from .models import Branch, Department




def branches(request):
    branches = Branch.objects.all()
    return render(request, 'company/branches.html', {'branches':branches})


def branch_details(request, branch_id):
    branch = Branch.objects.get(id=branch_id)
    departments = branch.departmentsBranch.filter(branch=branch)
    return render(request, 'company/branch_details.html', {'branch':branch, 'departments':departments})


def branch_create(request):
    if request.method == 'POST': 
        name = request.POST['branch-name']
        address = request.POST['branch-address']
        phone = request.POST['branch-phone']
        email = request.POST['branch-email']
        Branch.objects.create(
            name= name,
            address= address,
            phone= phone,
            email=email
        )
        return redirect('/company/')

    return render(request,'company/create_branch.html')



def branch_edit(request,id):
    object = Branch.objects.get(id=id)

    if request.method == 'POST':
        name = request.POST['branchName']

        address = request.POST['branchAddress']

        phone = request.POST['branchPhone']

        email = request.POST['branchEmail']

        
        object.name = name
        object.address= address
        object.phone= phone
        object.email=email
        object.save()
        
        return redirect(f'/company/{object.id}')

    return render(request,'company/branch_edit.html',{'object': object})

employee/views.py
from django.shortcuts import render
from django.views import generic

from .models import Employee ,Position
from .Forms import EmployeeForm , PositionForm


class EmployeeList(generic.ListView):
    model = Employee



class EmployeeDetail(generic.DeleteView):
    model = Employee



class createEmployee(generic.CreateView):
    model = Employee
    form_class = EmployeeForm



class UpdateEmployee(generic.UpdateView):
    model = Employee
    form_class = EmployeeForm



class DeleteEmployee(generic.DeleteView):
    model = Employee




class LestPosition(generic.ListView):
    model = Position




class DetailPosition(generic.ListView):
    model = Position




class CreatePosition(generic.ListView):
    model = Position
    form_class = PositionForm




class UpdatePosition(generic.ListView):
    model = Position
    form_class = PositionForm





class deletePosition(generic.ListView):
    model = Position

company/templates/company/branch_details.html
{% extends 'base.html'%}
{% block title%}
    <title>branch {{branch.name}}</title>
{%endblock title%}
{% block breadcrumb%}
    <li class="breadcrumb-item active" aria-current="page">
        <a href="{% url 'company:branches' %}">branches</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{branch.name}}</li>
{%endblock breadcrumb%}
{% block body%}
        <div style="background-color: rgb(235, 230, 230);border: 10px solid rgb(235, 230, 230);border-radius: 10px;">
            <dl class="row ml-4">
                <dt class="col-sm-3">Name:</dt>
                <dd class="col-sm-9">{{branch.name}}</dd>
                <dt class="col-sm-3">Address:</dt>
                <dd class="col-sm-9">{{branch.address}}</dd>
                <dt class="col-sm-3">Phone:</dt>
                <dd class="col-sm-9">{{branch.phone}}</dd>
                <dt class="col-sm-3">Email:</dt>
                <dd class="col-sm-9">{{branch.email}}</dd>
            </dl>
        </div>
        <br/>
        <a href="{% url 'company:branch_edit' branch.id %}" class="btn btn-outline-primary">Edit branch</a>

        <div class="mt-5">
        {% if departments %}
            <h2>Departments</h2>
            <table class="table ">
                <thead class="thead-dark">
                    <th>name</th>
                    <th>description</th>
                </thead>
                <tbody>
                    {% for department in departments %}
                    <tr>
                        <td>{{department.name}}</td>
                        <td>{{department.description}}</td>
                    </tr>
                    {%endfor%}
                </tbody>
            </table>
            <a href="#" class="btn btn-outline-primary">Edit Department</a>
        {% else %}
            <h1 class="alert-warning p-5"> No Departments found for this Branch {{branch.name}}</h1>
        
        {% endif %}
        </div>
{%endblock body%}

company/templates/company/branch_edit.html
{% extends 'base.html' %}

{% block title %}
    <title>Edit Branch {{ object.name }}</title>
{% endblock %}

{% block body %}
    <h1>Edit Branch</h1>
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="branchName">Branch Name</label>
            <input type="text" class="form-control" id="branchName" name="branchName" value="{{ object.name }}">
        </div>
        <div class="form-group">
            <label for="branchAddress">Branch Address</label>
            <input type="text" class="form-control" id="branchAddress" name="branchAddress" value="{{ object.address }}">
        </div>
        <div class="form-group">
            <label for="branchPhone">Branch Phone</label>
            <input type="text" class="form-control" id="branchPhone" name="branchPhone" value="{{ object.phone }}">
        </div>
        <div class="form-group">
            <label for="branchEmail">Branch Email</label>
            <input type="email" class="form-control" id="branchEmail" name="branchEmail" value="{{ object.email }}">
        </div>
        <button type="submit" class="btn btn-primary">Save changes</button>
    </form>
{% endblock body %}

company/templates/company/branches.html
{% extends 'base.html'%}

{% block title %}
    <title>branches</title>
{% endblock title %}

{% block breadcrumb %}
    <li class="breadcrumb-item active" aria-current="page">branches</li>
{% endblock breadcrumb %}

{% block body%}
    <table class="table table-hover">
        <thead class="thead-dark">
            <th>branch name</th>
            <th>branch phone</th>
            <th>branch mail</th>
            <th>departments</th>
        </thead>
        <tbody>
        {%for branche in branches %}
            <tr>
                <td><a href="{% url 'company:branchesDetails' branche.id %}">{{branche.name}}</a><br/>
                    <small class="text-muted">{{branche.address}}</small>
                </td>
                <td>{{branche.phone}}</td>
                <td>{{branche.email}}</td>
                <td>{{branche.departmentsBranch.all|length}}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'company:branch-create' %}" class="btn btn-outline-primary">new branche</a>
{% endblock body %}

company/templates/company/create_branch.html
{% extends 'base.html'%}

{%block title%}
<title>new branshe</title>
{%endblock%}

{% block breadcrumb%}
    <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'company:branches' %}">branches</a></li>
    <li class="breadcrumb-item active" aria-current="page">new branche</li>
{%endblock%}

{% block body%}
<form method="post" class="m-5">
    {% csrf_token %}
    <div class="form-group m-4">
        <label >Branche name</label>
        <input type="text" class="form-control" name="branch-name" required>
    </div>
    <div class="form-group m-4">
        <label >Branche address</label>
        <input type="text" class="form-control" name="branch-address" required>
    </div>
    <div class="form-group m-4">
        <label >Branche phone</label>
        <input type="text" class="form-control" name="branch-phone" required >
    </div>
    <div class="form-group m-4">
        <label>Branche Email address</label>
        <input type="email" class="form-control" name="branch-email" required>
      </div>
      <input type="submit" value="add branche" class="btn btn-outline-success"/>
</form>
{%endblock body%}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock title %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
</head>
<body>
    <div class="container mt-5" >
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                {% block breadcrumb %}
                {% endblock breadcrumb %}
            </ol>
        </nav>
        {% block body%}
        {% endblock body %}
    </div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>